### ISSUE TITLE
no function disconnect.socket in zmq

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/stateliner#4]
The function `rzmq::disconnect.socket` [used here](https://github.com/traitecoevo/stateliner/blob/master/R/stateliner.R#L28) does not seem to exist. Remove?

**Comment by richfitz** [comment]
I see a function of that name here:

```
> rzmq::disconnect.socket
function (socket, address) 
{
    invisible(.Call("disconnectSocket", socket, address, PACKAGE = "rzmq"))
}
<environment: namespace:rzmq>
> packageVersion("rzmq")
[1] ‘0.7.8’
```

**Comment by dfalster** [comment]
Ah ok. Seems [cran only has 0.7.7](https://cran.r-project.org/web/packages/rzmq/index.html) and that function was introduced in 0.7.8, which is available on [github](https://github.com/armstrtw/rzmq) but not cran. 

I see on github they've just released 0.8.0

**Comment by dfalster** [comment]
Should I change DESCRIPTION to require at least 0.7.8 and suggest installing "rzmq" from github (in readme)?

**Comment by dfalster** [comment]
Actually, installing via github is not straightforward either as requires zeromq.

**Comment by richfitz** [comment]
Weird. I don't recall installing from github but I evidently have (from a manual clone, and have installed libzmq).

Worse than requiring zeromq, the new version also requires C++11 which is a problem for Windows.  So I think that removing or conditionally removing the function is the right move.  For now, simply commenting it out with a note would be fine I think.
